version: '3.8'

services:
  web:
    build:
      context: ./authproject
      dockerfile: Dockerfile.prod
    volumes:
      - ./authproject:/app
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: "False"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
    restart: always
  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./authproject/prodstaticfiles:/app/prodstaticfiles
    depends_on:
      - web
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"