version: '3.8'

services:
  server:
    build:
      context: ./authproject
      dockerfile: Dockerfile.dev
    volumes:
      - ./authproject:/app
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
