FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    supervisor \
    cron \
    dos2unix \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /entrypoint.sh
RUN dos2unix /entrypoint.sh && chmod +x /entrypoint.sh

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

ENTRYPOINT ["/entrypoint.sh"]

CMD ["bash", "-c", "gunicorn server.wsgi:application --bind 0.0.0.0:8000 --workers 3"]
