FROM python:3.9

WORKDIR /app

RUN apt-get update && apt-get install -y supervisor cron dos2unix && apt-get clean

COPY entrypoint.sh /entrypoint.sh
RUN dos2unix /entrypoint.sh && chmod +x /entrypoint.sh

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

COPY . .

ENTRYPOINT ["/entrypoint.sh"]

CMD ["bash", "-c", "python manage.py runserver 0.0.0.0:8000"]
